services:
  postgres-wallet:
    image: postgres:16-alpine
    container_name: ilia-postgres-wallet
    environment:
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_wallet_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_user -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-users:
    image: postgres:16-alpine
    container_name: ilia-postgres-users
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_pass
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_user -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  ms-users:
    build:
      context: .
      dockerfile: packages/ms-users/Dockerfile
    container_name: ilia-ms-users
    environment:
      PORT: 3002
      GRPC_PORT: 50051
      DATABASE_URL: postgresql://users_user:users_pass@postgres-users:5432/users_db
      JWT_SECRET: ILIACHALLENGE
      JWT_INTERNAL_SECRET: ILIACHALLENGE_INTERNAL
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME}
      ADMIN_LAST_NAME: ${ADMIN_LAST_NAME}
    ports:
      - "3002:3002"
      - "50051:50051"
    depends_on:
      postgres-users:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy --schema=./packages/ms-users/prisma/schema.prisma && node packages/ms-users/dist/index.js"

  ms-wallet:
    build:
      context: .
      dockerfile: packages/ms-wallet/Dockerfile
    container_name: ilia-ms-wallet
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://wallet_user:wallet_pass@postgres-wallet:5432/wallet_db
      JWT_SECRET: ILIACHALLENGE
      JWT_INTERNAL_SECRET: ILIACHALLENGE_INTERNAL
      USERS_SERVICE_URL: ms-users:50051
    ports:
      - "3001:3001"
    depends_on:
      postgres-wallet:
        condition: service_healthy
      ms-users:
        condition: service_started
    command: sh -c "npx prisma migrate deploy --schema=./packages/ms-wallet/prisma/schema.prisma && node packages/ms-wallet/dist/index.js"

volumes:
  postgres_wallet_data:
  postgres_users_data:
